
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version: 
 - 11.3
 - 11.4.1
 - 11.5
 - 11.6
 - 12.0
target: 
 - docs
 - swiftlint
 - osx
 - osx-encryption
 - osx-object-server
 - ios-static
 - ios-dynamic
 - watchos
 - tvos
 - osx-swift
 - ios-swift
 - tvos-swift
 - catalyst
 - catalyst-swift
 - xcframework
 - cocoapods-osx
 - cocoapods-ios
 - cocoapods-ios-dynamic
 - cocoapods-watchos
 - swiftpm
 - swiftpm-address
 - swiftpm-thread
 - swiftpm-ios
configuration: 
 - Debug
 - Release

exclude:

  - xcode_version: 11.3
    target: docs
    configuration: Debug

  - xcode_version: 11.3
    target: docs
    configuration: Release

  - xcode_version: 11.4.1
    target: docs
    configuration: Debug

  - xcode_version: 11.4.1
    target: docs
    configuration: Release

  - xcode_version: 11.5
    target: docs
    configuration: Debug

  - xcode_version: 11.5
    target: docs
    configuration: Release

  - xcode_version: 11.6
    target: docs
    configuration: Debug

  - xcode_version: 11.6
    target: docs
    configuration: Release

  - xcode_version: 12.0
    target: docs
    configuration: Debug

  - xcode_version: 11.3
    target: swiftlint
    configuration: Debug

  - xcode_version: 11.3
    target: swiftlint
    configuration: Release

  - xcode_version: 11.4.1
    target: swiftlint
    configuration: Debug

  - xcode_version: 11.4.1
    target: swiftlint
    configuration: Release

  - xcode_version: 11.5
    target: swiftlint
    configuration: Debug

  - xcode_version: 11.5
    target: swiftlint
    configuration: Release

  - xcode_version: 11.6
    target: swiftlint
    configuration: Debug

  - xcode_version: 11.6
    target: swiftlint
    configuration: Release

  - xcode_version: 12.0
    target: swiftlint
    configuration: Debug

  - xcode_version: 11.3
    target: osx-encryption
    configuration: Debug

  - xcode_version: 11.4.1
    target: osx-encryption
    configuration: Debug

  - xcode_version: 11.4.1
    target: osx-encryption
    configuration: Release

  - xcode_version: 11.5
    target: osx-encryption
    configuration: Debug

  - xcode_version: 11.5
    target: osx-encryption
    configuration: Release

  - xcode_version: 11.6
    target: osx-encryption
    configuration: Debug

  - xcode_version: 11.6
    target: osx-encryption
    configuration: Release

  - xcode_version: 12.0
    target: osx-encryption
    configuration: Debug

  - xcode_version: 11.3
    target: osx-object-server
    configuration: Debug

  - xcode_version: 11.4.1
    target: osx-object-server
    configuration: Debug

  - xcode_version: 11.4.1
    target: osx-object-server
    configuration: Release

  - xcode_version: 11.5
    target: osx-object-server
    configuration: Debug

  - xcode_version: 11.5
    target: osx-object-server
    configuration: Release

  - xcode_version: 11.6
    target: osx-object-server
    configuration: Debug

  - xcode_version: 11.6
    target: osx-object-server
    configuration: Release

  - xcode_version: 12.0
    target: osx-object-server
    configuration: Debug

  - xcode_version: 11.3
    target: ios-static
    configuration: Debug

  - xcode_version: 11.4.1
    target: ios-static
    configuration: Debug

  - xcode_version: 11.4.1
    target: ios-static
    configuration: Release

  - xcode_version: 11.5
    target: ios-static
    configuration: Debug

  - xcode_version: 11.5
    target: ios-static
    configuration: Release

  - xcode_version: 11.6
    target: ios-static
    configuration: Debug

  - xcode_version: 11.6
    target: ios-static
    configuration: Release

  - xcode_version: 12.0
    target: ios-static
    configuration: Debug

  - xcode_version: 11.3
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 11.4.1
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 11.4.1
    target: ios-dynamic
    configuration: Release

  - xcode_version: 11.5
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 11.5
    target: ios-dynamic
    configuration: Release

  - xcode_version: 11.6
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 11.6
    target: ios-dynamic
    configuration: Release

  - xcode_version: 12.0
    target: ios-dynamic
    configuration: Debug

  - xcode_version: 11.3
    target: watchos
    configuration: Debug

  - xcode_version: 11.4.1
    target: watchos
    configuration: Debug

  - xcode_version: 11.4.1
    target: watchos
    configuration: Release

  - xcode_version: 11.5
    target: watchos
    configuration: Debug

  - xcode_version: 11.5
    target: watchos
    configuration: Release

  - xcode_version: 11.6
    target: watchos
    configuration: Debug

  - xcode_version: 11.6
    target: watchos
    configuration: Release

  - xcode_version: 12.0
    target: watchos
    configuration: Debug

  - xcode_version: 11.3
    target: tvos
    configuration: Debug

  - xcode_version: 11.4.1
    target: tvos
    configuration: Debug

  - xcode_version: 11.4.1
    target: tvos
    configuration: Release

  - xcode_version: 11.5
    target: tvos
    configuration: Debug

  - xcode_version: 11.5
    target: tvos
    configuration: Release

  - xcode_version: 11.6
    target: tvos
    configuration: Debug

  - xcode_version: 11.6
    target: tvos
    configuration: Release

  - xcode_version: 12.0
    target: tvos
    configuration: Debug

  - xcode_version: 11.3
    target: ios-swift
    configuration: Debug

  - xcode_version: 11.4.1
    target: ios-swift
    configuration: Debug

  - xcode_version: 11.4.1
    target: ios-swift
    configuration: Release

  - xcode_version: 11.5
    target: ios-swift
    configuration: Debug

  - xcode_version: 11.5
    target: ios-swift
    configuration: Release

  - xcode_version: 11.6
    target: ios-swift
    configuration: Debug

  - xcode_version: 11.6
    target: ios-swift
    configuration: Release

  - xcode_version: 12.0
    target: ios-swift
    configuration: Debug

  - xcode_version: 11.3
    target: tvos-swift
    configuration: Debug

  - xcode_version: 11.4.1
    target: tvos-swift
    configuration: Debug

  - xcode_version: 11.4.1
    target: tvos-swift
    configuration: Release

  - xcode_version: 11.5
    target: tvos-swift
    configuration: Debug

  - xcode_version: 11.5
    target: tvos-swift
    configuration: Release

  - xcode_version: 11.6
    target: tvos-swift
    configuration: Debug

  - xcode_version: 11.6
    target: tvos-swift
    configuration: Release

  - xcode_version: 12.0
    target: tvos-swift
    configuration: Debug

  - xcode_version: 11.3
    target: catalyst
    configuration: Debug

  - xcode_version: 11.4.1
    target: catalyst
    configuration: Debug

  - xcode_version: 11.4.1
    target: catalyst
    configuration: Release

  - xcode_version: 11.5
    target: catalyst
    configuration: Debug

  - xcode_version: 11.5
    target: catalyst
    configuration: Release

  - xcode_version: 11.6
    target: catalyst
    configuration: Debug

  - xcode_version: 11.6
    target: catalyst
    configuration: Release

  - xcode_version: 12.0
    target: catalyst
    configuration: Debug

  - xcode_version: 11.3
    target: catalyst-swift
    configuration: Debug

  - xcode_version: 11.4.1
    target: catalyst-swift
    configuration: Debug

  - xcode_version: 11.4.1
    target: catalyst-swift
    configuration: Release

  - xcode_version: 11.5
    target: catalyst-swift
    configuration: Debug

  - xcode_version: 11.5
    target: catalyst-swift
    configuration: Release

  - xcode_version: 11.6
    target: catalyst-swift
    configuration: Debug

  - xcode_version: 11.6
    target: catalyst-swift
    configuration: Release

  - xcode_version: 12.0
    target: catalyst-swift
    configuration: Debug

  - xcode_version: 11.3
    target: xcframework
    configuration: Debug

  - xcode_version: 11.3
    target: xcframework
    configuration: Release

  - xcode_version: 11.4.1
    target: xcframework
    configuration: Debug

  - xcode_version: 11.4.1
    target: xcframework
    configuration: Release

  - xcode_version: 11.5
    target: xcframework
    configuration: Debug

  - xcode_version: 11.5
    target: xcframework
    configuration: Release

  - xcode_version: 11.6
    target: xcframework
    configuration: Debug

  - xcode_version: 11.6
    target: xcframework
    configuration: Release

  - xcode_version: 12.0
    target: xcframework
    configuration: Debug

  - xcode_version: 11.3
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 11.5
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 11.6
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 12.0
    target: cocoapods-osx
    configuration: Debug

  - xcode_version: 11.3
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-ios
    configuration: Release

  - xcode_version: 11.5
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 11.5
    target: cocoapods-ios
    configuration: Release

  - xcode_version: 11.6
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 11.6
    target: cocoapods-ios
    configuration: Release

  - xcode_version: 12.0
    target: cocoapods-ios
    configuration: Debug

  - xcode_version: 11.3
    target: cocoapods-ios-dynamic
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-ios-dynamic
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-ios-dynamic
    configuration: Release

  - xcode_version: 11.5
    target: cocoapods-ios-dynamic
    configuration: Debug

  - xcode_version: 11.5
    target: cocoapods-ios-dynamic
    configuration: Release

  - xcode_version: 11.6
    target: cocoapods-ios-dynamic
    configuration: Debug

  - xcode_version: 11.6
    target: cocoapods-ios-dynamic
    configuration: Release

  - xcode_version: 12.0
    target: cocoapods-ios-dynamic
    configuration: Debug

  - xcode_version: 11.3
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-watchos
    configuration: Release

  - xcode_version: 11.5
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 11.5
    target: cocoapods-watchos
    configuration: Release

  - xcode_version: 11.6
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 11.6
    target: cocoapods-watchos
    configuration: Release

  - xcode_version: 12.0
    target: cocoapods-watchos
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.4.1
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.4.1
    target: swiftpm
    configuration: Release

  - xcode_version: 11.5
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.5
    target: swiftpm
    configuration: Release

  - xcode_version: 11.6
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.6
    target: swiftpm
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-address
    configuration: Release

  - xcode_version: 11.4.1
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.4.1
    target: swiftpm-address
    configuration: Release

  - xcode_version: 11.5
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.5
    target: swiftpm-address
    configuration: Release

  - xcode_version: 11.6
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.6
    target: swiftpm-address
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 11.4.1
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.4.1
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 11.5
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.5
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 11.6
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.6
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 11.4.1
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 11.4.1
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 11.5
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 11.5
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 11.6
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 11.6
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm-ios
    configuration: Debug
