disabled_rules:
    - line_length

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 12

identifier_name:
  excluded:
    - id

# paths to ignore during linting.
excluded: 
  - Carthage
  - Pods