disabled_rules:
    - line_length
    - todo

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 12

identifier_name:
  excluded:
    - id
    - vc
    - i
    - x
    - y
    - tv
    - to

# paths to ignore during linting.
excluded: 
  - Carthage
  - Pods