default_platform(:ios)

platform :ios do


  desc "Build and upload a new build of Notifire Mock to TestFlight (locally - apple ID sign in needed)"
  lane :local_beta_mock do

    sync_code_signing(
      type: "appstore",
      app_identifier: ["com.dvdblk.Notifire.mock.tf", "com.dvdblk.Notifire.mock.tf.NotificationServiceExtension"]

    )

    increment_build_number

    build_app(
      workspace: "Notifire.xcworkspace", 
      scheme: "Notifire Mock TF", 
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Notifire.xcodeproj"
    )
    
    upload_to_testflight
  end

  desc "Build and upload a new build of Notifire to TestFlight (locally - apple ID sign in needed)"
  lane :local_beta do

    sync_code_signing(
      type: "appstore",
      app_identifier: ["com.dvdblk.Notifire", "com.dvdblk.Notifire.NotificationServiceExtension"]
    )

    increment_build_number

    build_app(
      workspace: "Notifire.xcworkspace",
      scheme: "Notifire",
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Notifire.xcodeproj"
    )

    upload_to_testflight
  end
end
