default_platform(:ios)

platform :ios do


  desc "Build and upload a new build of Notifire Mock to TestFlight (locally - apple ID sign in needed)"
  lane :local_beta_mock do

    sync_code_signing(
      type: "appstore",
      app_identifier: ["com.dvdblk.Notifire.mock.tf", "com.dvdblk.Notifire.mock.tf.NotificationServiceExtension"]

    )

    increment_build_number

    build_app(
      workspace: "Notifire.xcworkspace", 
      scheme: "Notifire Mock TF", 
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Notifire.xcodeproj"
    )
    
    upload_to_testflight
  end

  desc "Test lane"
  lane :testicek do

  end

  desc "Build and upload a new build of Notifire to TestFlight (locally - apple ID sign in needed)"
  lane :local_testflight do

    ensure_git_branch(
      branch: '^develop$'
    )

    ensure_git_status_clean

    sync_code_signing(
      type: "appstore",
      app_identifier: ["com.dvdblk.Notifire", "com.dvdblk.Notifire.NotificationServiceExtension"]
    )

    increment_build_number

    build_app(
      workspace: "Notifire.xcworkspace",
      scheme: "Notifire",
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Notifire.xcodeproj"
    )

    upload_to_testflight

    build_number = get_build_number(xcodeproj: "Notifire.xcodeproj")

    path = "."
    git_add(
      path: path
    )

    git_commit(
      path: path,
      message: "Upload to testflight (build " + build_number + ")"
    )

    push_to_git_remote
  end
end
